DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'         # output folder name used for saving the model, logs and inference results
WANDB_ID        : 'kco0zfvr'        # id of wandb run to resume.
INIT_EPOCH      : 5

MODEL:                                    
  NAME          : Lawin                                           # name of the model you are using
  BACKBONE      : MiT-B3                                                 # model variant
  PRETRAINED    : 'checkpoints/backbones/MIT/mit_b3.pth'              # backbone model's weight 

DATASET:
  NAME          : CIHP                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/home/shivam/'                                   # dataset root path
  IGNORE_LABEL  : 255

TRAIN:
  IMAGE_SIZE    : [512, 512]    # training image size in (h, w)
  BATCH_SIZE    : 15               # batch size used to train
  EPOCHS        : 50             # number of epochs to train
  EVAL_INTERVAL : 2              # evaluation interval during training
  AMP           : true           # use AMP in training
  DDP           : false           # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name (ohemce, ce, dice)
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.001           # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 5               # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  IMAGE_SIZE    : [512, 512]                            # evaluation image size in (h, w)                       
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
